name: Docker image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and run the Docker image
      run: |
        docker build -t go-issue-38669 .
        docker run go-issue-38669
